#pragma once
#include "CommCtrl.h"
#include <Commdlg.h>

#define SAFE_DELETE_ALL(_obj) if( (_obj) != NULL ) delete (_obj); (_obj) = NULL;
#define SAFE_DELETE_OBJECT(_obj) if( (_obj) != NULL ) DeleteObject(_obj); (_obj) = NULL;

#define DEFAULTTOOLSW 160
#define DEFAULTBORDER 5
#define DEFAULTSMALLBORDER 0
#define DEFAULTSTEPBACKTRACK 1
#define DEFAULTSTEPBACKRADIO 1

#define DEFAULTWINDOWW 1000
#define DEFAULTWINDOWH 920

#define DEFAULTWINDOWWBOR 20
#define DEFAULTWINDOWHBOR 60

#define DEFAULTSTATICW (DEFAULTTOOLSW - (DEFAULTBORDER * 2))
#define DEFAULTSTATICH 20
#define DEFAULTTRACKW (DEFAULTTOOLSW - (DEFAULTBORDER * 2))
#define DEFAULTTRACKH 25
#define DEFAULTRADIOW (DEFAULTTOOLSW - (DEFAULTBORDER * 2))
#define DEFAULTRADIOH 20
#define DEFAULTCHECKW (DEFAULTTOOLSW - (DEFAULTBORDER * 2))
#define DEFAULTCHECKH 20
#define DEFAULTBUTTONW (DEFAULTTOOLSW - (DEFAULTBORDER * 2))
#define DEFAULTBUTTONH 25

#define DEFAULTBORDERNUMBERS 2
